sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

language: php

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - COMPOSER_OPTIONS="--prefer-stable"
    - PHPSTAN_CONFIG=phpstan.neon

matrix:
  include:
    - php: 7.3
    - php: 7.1
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable" PHPSTAN_CONFIG=phpstan-php-71.neon
    - php: 7.1
      env: SYMFONY_REQUIRE="4.4.*" PHPSTAN_CONFIG=phpstan-php-71.neon
    - php: 7.4
      env: SYMFONY_REQUIRE="5.0.*"
    - php: 7.4
      env: SYMFONY_REQUIRE="5.1.*"
    - php: 7.2
      env: COMPOSER_OPTIONS=""

before_install:
  - phpenv config-rm xdebug.ini
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - composer update $COMPOSER_OPTIONS
  - vendor/bin/simple-phpunit install

script:
  - vendor/bin/php-cs-fixer fix --diff --dry-run
  - vendor/bin/phpstan analyze -c $PHPSTAN_CONFIG
  - vendor/bin/simple-phpunit
